FROM bcbio/bcbio:latest

RUN locale-gen en_US.UTF-8

RUN /usr/local/bin/bcbio_conda remove --force --yes bcbio-nextgen

ADD ./ /bcbio-nextgen

ENV PATH /usr/local/share/bcbio-nextgen/anaconda/bin:$PATH


# Add the dependencies to requirements!!! 
RUN conda install -c conda-forge google-api-python-client

WORKDIR /bcbio-nextgen

RUN rm -rf ~/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio
RUN rm -rf ~/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-*
RUN pip install -qe . 
